services:
  app:
    build: .
    container_name: micronaut-demo
    restart: always
    ports:
      - "8000:8000"
    environment:
      - MICRONAUT_SERVER_PORT=8000
      - JAVA_OPTS=-Xmx256m
#      - JAVA_OPTS=-Xmx256m -Xms128m
    networks:
      - micronaut-network
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M

networks:
  micronaut-network:
    driver: bridge