services:
  app:
    build: .
    container_name: micronaut-demo
    restart: always
    ports:
      - "8000:8000"
    environment:
      - MICRONAUT_SERVER_PORT=8000
      - JAVA_OPTS=-Xmx256m
#      - JAVA_OPTS=-Xmx256m -Xms128m
    networks:
      - micronaut-network
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=booksdb
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - micronaut-network
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql-data:

networks:
  micronaut-network:
    driver: bridge