micronaut:
  application:
    name: demo
  server:
    port: 8000
    cors:
      enabled: true
      configurations:
        web:
          allowedOrigins:
            - http://localhost:3000
          allowedMethods:
            - GET
            - POST
            - PUT
            - DELETE
          allowedHeaders:
            - Content-Type
            - Authorization
          exposedHeaders:
            - Content-Type
            - Authorization
          allowCredentials: true
          maxAge: 3600
netty:
  default:
    allocator:
      max-order: 3
logger:
  levels:
    com.example: DEBUG
    io.micronaut: INFO
    io.micronaut.http.client: DEBUG
